import { Poppins } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "./context/AuthContext";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased bg-background text-foreground`}>
        <AuthContextProvider>
          <div className="min-h-screen w-full">
            {children}
          </div>
        </AuthContextProvider>
      </body>
    </html>
  );
}